### ISSUE TITLE
setInterruptControl doesn't work

### ISSUE THREAD

**Issue by hmboonstra** [sparkfun/SparkFun_TSL2561_Arduino_Library#1]
The setInterruptControl doesn't work. It seems that the boolean operators used to construct the final word based on the control and persist parameters are the wrong way round. I think it should be:

`((control & 0B00000011) << 4) | (persist & 0B00001111)`

**Comment by amanpreetjpr** [comment]
Hey,
Did the library work after changes?

**Comment by hmboonstra** [comment]
We are currently running on the changed library and works as expected (for us).

**Comment by Grahldg** [comment]
Thank you for notifying us of this issue.  Unfortunately this product is retired and this repository will no longer be maintained.  The repository will be archived for reference.  If you have any further questions or issues with this product please consult our [forum](https://forum.sparkfun.com/).
